class ProductList {
  static List<Map> MyList = [
    {
      'image': 'assets/images/B_jacket.jpg',
      'name': 'Brown Jacket',
      'originalPrice': 150,
      'discountedPrice': 120,
      'discountPercentage': 20,
      'category': 'Jacket',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/G_shirt.jpg',
      'name': 'Girl shirt',
      'originalPrice': 200,
      'discountedPrice': 150,
      'discountPercentage': 25,
      'category': 'Shirt',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/B_shirt.jpg',
      'name': 'Brown Shirt',
      'originalPrice': 200,
      'discountedPrice': 150,
      'discountPercentage': 25,
      'category': 'Shirt',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/girl_jacket.jpg',
      'name': 'Brown Jacket',
      'originalPrice': 1000,
      'discountedPrice': 700,
      'discountPercentage': 30,
      'category': 'Jacket',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/black_girl_jacket.jpg',
      'name': 'Black Jacket',
      'originalPrice': 100,
      'discountedPrice': 70,
      'discountPercentage': 30,
      'category': 'Jacket',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/brown_t.jpg',
      'name': 'Brown T-shirt',
      'originalPrice': 500,
      'discountedPrice': 350,
      'discountPercentage': 30,
      'category': 'Shirt',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/boys_pant.jpg',
      'name': 'Boys Pants',
      'originalPrice': 500,
      'discountedPrice': 350,
      'discountPercentage': 30,
      'category': 'Pant',
      'isWishlisted': false,
    },
    {
      'image': 'assets/images/boys_pant1.jpg',
      'name': 'Boys Pant',
      'originalPrice': 500,
      'discountedPrice': 350,
      'discountPercentage': 30,
      'category': 'Pant',
      'isWishlisted': false,
    },
  ];
  static List imglist = [
    'assets/images/B_shirt.jpg',
    'assets/images/G_shirt.jpg',
    'assets/images/B_suit.jpg',
    'assets/images/brown_t.jpg',
    'assets/images/black_girl_jacket.jpg',
  ];
}
